### ISSUE TITLE
Freeze and error when trying to export a movie

### ISSUE THREAD

**Issue by jocdiazm** [ArteliaTelemac/PostTelemac#10]
Dear DevTeam,

I'm having trouble to export a simple movie in postTelemac. Just adding any slf results, default settings, making a simple print composer of the map and clicking export makes in the log output message:

`Tue Oct 04 11:40:40 2016 Film - NE PAS MODIFIER L'ESPACE DESSIN DURANT L'OPERATION 
`
`
Tue Oct 04 11:40:40 2016 - Film - creation du fichier [note: a path goes here]
`
`make movie : 'NoneType' object has no attribute 'canvas'
`

Then it "freezes" an image in the canvas and then the instance of the slf is unusable (cant modify or update anything), so a re-launch of Qgis its necessary.

. I'm running:
QGis 2.14.3
Windows 7 x64 
(and also happens in linux with QGis 2.16)

Regards,

José D.

**Comment by ccoulet** [comment]
Hi
In fact, it works if you add a temporal graph in your composer but crash if you don't have any graph.
We will correct this bug soon and release a new version of the plugin

Regards

**Comment by patricev** [comment]
Hi
fixed in 0.1.10 release - coming as soon as qgis dev team approve it ! 
Regards
