### ISSUE TITLE
[LINUX] Some Path and python subprocess issues

### ISSUE THREAD

**Issue by jocdiazm** [ArteliaTelemac/PostTelemac#11]
Dear DevTeam,

I installed the latest Github version of postelemac and tried the "simple export video" test that reported yesterday, now with success ( I guess Ineed to do the "real world" case now...) but in the process I noticed a few things that perhaps are related to the current working OS (LINUX) that should be reported:

**1.  Qgis, when loading the installed plugins cant import the module "progressbar" ("utils" module in general)**

This is due to that there is an existent "utils" module installed in python system that takes precedence in PYTHONPATH system variable and (of course) there is no "progressbar" module there. I guess "utils" is a pretty common name among developers so I believe this happens a lot...

**workaround:1** Renaming the utils module of posttelemac.I changed the name of the folder utils to utils2, and all the "import" statements.

**workaround2**: in the terminal i set the precedence of the pythonpath before calling qgis :

`export PYTHONPATH=~/.qgis2/python/plugins/PostTelemac/libs_telemac:$PYTHONPATH`

**2. There is a "film-erreur" log when exporting video (I do have ffmpeg correctly installed)**

This happens because in the line  231 of /libs/posttelemac_util_animation.py :

`
res = subprocess.call(cmd, shell = True, stdin=subprocess.PIPE, stdout=f, stderr=f)
`

the variable _cmd_ is a list and subprocess does  some [confusing moves](http://stackoverflow.com/questions/15109665/subprocess-call-using-string-vs-using-list) (reading the comment in line 230...had any windows issues before?)  that were solved when passing a _string_ rather than a _list_ or changing the **shell** argument in that line to **False**.

Thanks for your time!

Edit: I'll be testing all the features of postTelemac in both Windows and Linux and will  report the relevant issues or enhancements, my apologies for future inconveniences!

Regards,

José.

**Comment by patricev** [comment]
Thanks a lot for reporting bugs.
Your comments are added to github. Waiting a little to do a new official version.
Regards,
Patrice
