### ISSUE TITLE
Using MDAL for QGIS 3 port

### ISSUE THREAD

**Issue by saberraz** [ArteliaTelemac/PostTelemac#16]
Dear developer,

If you are planning to migrate your plugin to QGIS 3, I suggest to port the Telemac output format to MDAL, which is integrated to QGIS master:
https://github.com/lutraconsulting/MDAL
https://github.com/qgis/QGIS/tree/master/external/mdal

An example of MDAL layer in QGIS:
https://github.com/qgis/QGIS/pull/7313

For more background info:
https://github.com/qgis/QGIS-Enhancement-Proposals/issues/119

**Comment by ccoulet** [comment]
The Telemac output format will not change at least in a near future...
Nevertheless, it's maybe possible to add the Telemac File format in the list of supported format or as it seems to be indicate in the QEP, to develop a python plugin for this.
It could be great if we have some guidelines (HowTo) to develop a new reader or a new plugin.

**Comment by saberraz** [comment]
Once you add Telemac to MDAL, you can then load the layer as a mesh layer:
`QgsMeshLayer (“path/to/telemacfile”, “my layer”, “mdal”)`

Here is more info:
https://qgis.org/api/classQgsMeshLayer.html

You can then access both the native mesh and vectors and also the time:
https://twitter.com/lutraconsulting/status/1018809991103500288

In future, when we add 3D support for mesh layer, your layer will magically appear in 3D canvas with the correct z scale (e.g. water levels will appear on top of the dtm).

**Comment by PeterPetrik** [comment]
MDAL(QGIS) now natively supports telemac files https://qgis.org/downloads/macos/
