### ISSUE TITLE
Please specify dependencies

### ISSUE THREAD

**Issue by pcav** [ArteliaTelemac/PostTelemac#2]
So users will be warned to install them before installing the plugin.

**Comment by pcav** [comment]
It is unclear which lib should be installed for NavigationToolbar2QTAgg. Please help users.
Thanks.

**Comment by patricev** [comment]
Required libraries are now specified in the description of the plugin (metadata.txt) . It's also written in the wiki.
For information, NavigationToolbar2QTAgg is in default matplotlib library.
Sincerely Yours
