### ISSUE TITLE
No plugin named "PostTelemac"

### ISSUE THREAD

**Issue by AntoninMazoyer** [ArteliaTelemac/PostTelemac#4]
Hi,

I could not find the plugin "PostTelemac" in the QGIS plugin menu. It had been deleted? There is an other way to install it?

Thank you

**Comment by patricev** [comment]
Hi,
The plugin is "experimental'. 
So go to "Plugins menu" \"Manage and install plugins"\"settings tab" and click on "Show also experimental plugins". Reload the plugins and i think it will show.
Regards,

**Comment by AntoninMazoyer** [comment]
Thank you for your quick reply
Regards,
