### ISSUE TITLE
Problem with the movie maker

### ISSUE THREAD

**Issue by AntoninMazoyer** [ArteliaTelemac/PostTelemac#5]
Hi,

I've tried the different tools of the plugin and globaly it has operated well. However, I have a problem with the movie maker. It starts normaly by creating the preview and processing the iterations but there is an error when it tries to create the AVI Files. Please find screenshot of the LOG below.

Regards,

![t2d_qgis_movielog](https://cloud.githubusercontent.com/assets/17158348/12948745/50eacd36-d004-11e5-8129-cce620bd1684.PNG)

**Comment by patricev** [comment]
Hi,
Maybe two possible causes:
1 - have you installed the 'ffmpeg' library ?
2 - if you try to make a movie with a value of "frame per second" lower than 3, an error could be raised.

Regards,

**Comment by AntoninMazoyer** [comment]
Hi,
The first point caused the problem, the "ffmpeg" was not installed.
Thanks you for your help
