### ISSUE TITLE
Format of speed arrows and bug

### ISSUE THREAD

**Issue by AntoninMazoyer** [ArteliaTelemac/PostTelemac#6]
Hello,

I just do a suggestion about the format of speed arrows. It would be fine to have the hability to define a colour ramp (or black and white ramp). Moreover, it miss an option to fix a constant norm for the arrows.

Others issues:
1) in the new version 0.14, there is now impossible to open a .geo selafin file due to line 278 of 
"post_telemac_pluginlayer.py" because there are not water depth neither free surface parameters in those kind of files. When we coment the loop "if", it works well.
2) In some .res selafin file, we use a local landmark. In order to inform the origine of the coordinate system, we use the keyword "cordonnées de l'origine". in the cas file. At the line 87 of "posttelemac_selafin_parser.py" file, we've changed to:
"return (self.hydraufile.MESHX+self.hydraufile.IPARAM[2], self.hydraufile.MESHY+self.hydraufile.IPARAM[3])"

Thanks
Regards

**Comment by patricev** [comment]
Hello, 

OK for the other issues, it will be included in next release.

For the speed arrows, i don't exactly understand what you suggest. Do you want the same color ramp as for contour ? And for the constant norm, there is already a constant norm in meters. Do yo want it in pixel ?

Regards.

**Comment by AntoninMazoyer** [comment]
Hello,

It's possible I don't understand well but I have feeling that the norm of the arrow depends obligatory of the speed value in m/s. The goal is to show all the arrows with the same norm in order to show only the direction of the flow. Relative to the color, there are not habilities to set a personalized color ramp as for the other parameters, and for consequences to have a unic color for example (black).

![image](https://cloud.githubusercontent.com/assets/17158348/14778603/28ad6c56-0ad4-11e6-8667-1b99f9602bde.png)

I hope you will understand. It's just a suggestion. Thanks in advance

Regards,

**Comment by patricev** [comment]
I close this bug, because I think it's fixed
Regards
