### ISSUE TITLE
Movie Tool

### ISSUE THREAD

**Issue by twicetwice** [ArteliaTelemac/PostTelemac#7]
Good Afternoon,
I have a problem creating a video with the movie tool. I think that I did all the steps correctly, like it is described here:
https://github.com/ArteliaTelemac/PostTelemac/wiki
But after the last iteration, there is the message "... Film - erreur" in the Log. I can not figure out why!
Does somebody have the same problem or can help me?
Thank you in advance
QGIS 2.14.1
PostTelemac 0.1.4
Windows 7
Input *.slf (telemac) + background *.tif

**Comment by patricev** [comment]
Hi, 
Sometimes it happens when the fps (frame per seconds) is too small. Could you try with a higher fps (10 for exemple ?) and tell me if it solves the problem ?
Regards,

**Comment by twicetwice** [comment]
Hello patricev,
thank you for your fast answer.
I tried various combinations up to 20 fps, but I still get the same error message!
I have even tried to use smaller *.slf files as input. Nothing!
I do not use a "Graph insert", may this cause a problem?
The only thing left would be the composer i use. Are there special configurations to consider?
Regards

**Comment by AntoninMazoyer** [comment]
Hello twicetwice,

I had a similar problem. The cause was the absence of ffmpeg library. In this case, It work the movie but it's impossible to encode the movie at the end. Maybe, you've not installed the library. The wiki explains well the steps to install it using the advanced installer of Qgis.
regards

**Comment by twicetwice** [comment]
Hello AntoninMazoyer,
thank you. That is the **solution** for my problem!
I have been trying to install the ffmpeg library seperatly but it did not work out.
With this advanced installer (osgeo4w-setup-x86_64) everything works just fine!
So here the links again for everybody else:
Download osgeo4w-setup
http://www.qgis.org/en/site/forusers/download.html
Follow INSTALLATION instructions
https://github.com/ArteliaTelemac/PostTelemac/wiki
good luck and good night
