### ISSUE TITLE
Graph with a moving line for showing the time of simulation - MOVIE TOOL

### ISSUE THREAD

**Issue by twicetwice** [ArteliaTelemac/PostTelemac#8]
Hello,
I am trying to add a graph with a moving line for showing the time of simulation in my movie. I was following the instructions on wiki and created a FLOW GRAPH and an image in the print composer.
Then I slected the image ID in GRAPH INSERT (MOVIE TOOL).
When I launch DO MOVIE there is this message:
_Sun May 15 14:45:49 2016 Film - NE PAS MODIFIER L'ESPACE DESSIN DURANT L'OPERATION 
Sun May 15 14:45:49 2016 - Film - creation du fichier E:/...\Results.avi
make movie : Format "jpg" is not supported.
Supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz._
I have all the libraries installed like it is described on wiki (Matplotlib included). 
Does anybody have an idea what the problem could be?
Thank you

**Comment by patricev** [comment]
Hello,
Maybe you could try to    check if installed / install    the "jpg" libraries with the advanced osgeo installer. The libraries are : 
libjpeg, libjpeg12 and openjpeg.
Tell me if it works.
Regards

**Comment by twicetwice** [comment]
Hello patricev
the libraries have already been installed. I reinstalled them, but there is still the same error coming up!
Regards

**Comment by twicetwice** [comment]
Hello,
well it works!
I installed some random Libs in the advanced asgeo installer. I didn´t really know what I was doing.
So I can´t say which one was the missing one, or maybe more then one.
Here is my List of installed Libs ("Keep" means that it is installed):
Regards
PS Thank you for Posttelemac
![1](https://cloud.githubusercontent.com/assets/18900711/15406826/53eaf540-1e08-11e6-9877-0c3dc0db0b89.PNG)
![2](https://cloud.githubusercontent.com/assets/18900711/15406828/56d26de2-1e08-11e6-9b02-16d5e5d38a16.PNG)
![3](https://cloud.githubusercontent.com/assets/18900711/15406830/58ef3862-1e08-11e6-8a5e-76e526753087.PNG)
![4](https://cloud.githubusercontent.com/assets/18900711/15406833/5a744f7e-1e08-11e6-94da-24f08a71dace.PNG)
